[pytest]
# 1. 配置默认执行参数
# -v: 详细模式  -s: 打印代码中的 print 信息
# --alluredir: 指定 allure 原始数据生成路径
# --clean-alluredir: 每次运行前清空旧的报告数据
addopts = -vs --alluredir=./allure-results --clean-alluredir --cov=app --cov-report=term-missing --cov-report=html

# 2. 配置测试搜索路径
# 告诉 pytest 只去 tests 目录下找用例，提升启动速度
testpaths = tests

# 3. 配置测试文件、类、函数的命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 4. 解决控制台 Unicode 乱码问题 (核心！)
# 设置为 True 后，DDT 数据池里的中文描述将不再显示为 \uXXXX，而是直接显示中文
disable_test_id_escaping_and_forfeit_all_rights_to_complain = True

# 5. 配置日志格式 (可选，方便调试)
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S